// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nowka.Data;

namespace Nowka.Migrations
{
    [DbContext(typeof(TimesheetContext))]
    partial class TimesheetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Nowka.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Firma");

                    b.Property<int?>("GroupHeadId");

                    b.Property<string>("Name");

                    b.Property<DateTime?>("Termin");

                    b.HasKey("Id");

                    b.HasIndex("GroupHeadId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Nowka.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Stanowisko");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Nowka.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StatusName");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Nowka.Models.Timesheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndHour");

                    b.Property<string>("OpisCzynnosci");

                    b.Property<int?>("PracownikId");

                    b.Property<int?>("ProjektId");

                    b.Property<DateTime>("StartHour");

                    b.HasKey("Id");

                    b.HasIndex("PracownikId");

                    b.HasIndex("ProjektId");

                    b.ToTable("Timesheet");
                });

            modelBuilder.Entity("Nowka.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Imie")
                        .IsRequired();

                    b.Property<string>("Nazwisko")
                        .IsRequired();

                    b.Property<string>("Password");

                    b.Property<int?>("UprawnieniaId");

                    b.HasKey("Id");

                    b.HasIndex("UprawnieniaId");

                    b.ToTable("Worker");
                });

            modelBuilder.Entity("Nowka.Models.Project", b =>
                {
                    b.HasOne("Nowka.Models.Worker", "GroupHead")
                        .WithMany("ParticipatingProjects")
                        .HasForeignKey("GroupHeadId");
                });

            modelBuilder.Entity("Nowka.Models.Timesheet", b =>
                {
                    b.HasOne("Nowka.Models.Worker", "Pracownik")
                        .WithMany()
                        .HasForeignKey("PracownikId");

                    b.HasOne("Nowka.Models.Project", "Projekt")
                        .WithMany()
                        .HasForeignKey("ProjektId");
                });

            modelBuilder.Entity("Nowka.Models.Worker", b =>
                {
                    b.HasOne("Nowka.Models.Role", "Uprawnienia")
                        .WithMany()
                        .HasForeignKey("UprawnieniaId");
                });
#pragma warning restore 612, 618
        }
    }
}
